
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  apkPath: com.companyname.internettracker.mobileapp.apk
  solutionPath: internet tracker.sln
  projectPath: src/InternetTracker.MobileApp/InternetTracker.MobileApp.Android
  configPath: src/InternetTracker.MobileApp/InternetTracker.MobileApp/Config.nogit.cs
  configNameSpace: InternetTracker.MobileApp
  artifactName: publishedApk
  appCenterSlug: live.neville-live.com/Internet-Tracker
  keyStoreFile: internet.jks

# to be defined as secrets:
  # keystore.password
  # key.password

stages:
  - stage: Build
    displayName: Build App
    jobs:

      - job: XamarinCompile
        displayName: Building xamarin android

        steps:

          - task: file-creator@5
            displayName: Create config file
            inputs:
              filepath: $(configPath)
              fileoverwrite: true
              filecontent: |
                namespace $(configNameSpace)
                {
                    static partial class Config
                    {
                        static Config()
                        {
                            Endpoint = "http://192.168.0.140:5020";
                            AppCenter = "$(secrets.appCenter)";
                        }
                    }
                }


          - task: NuGetToolInstaller@1

          
          - task: NuGetCommand@2
            inputs:
              command: 'restore'
          
          - task: android-manifest-version@1
            inputs:
              sourcePath: $(projectPath)/Properties/AndroidManifest.xml
              printFile: true
              versionCode: $(Build.BuildId)
              versionName: 1.0.$(Build.BuildId)

          - task: XamarinAndroid@1
            inputs:
              projectFile: $(projectPath)/*.csproj
              outputDirectory: '$(outputDirectory)'
              configuration: '$(buildConfiguration)'
              msbuildVersionOption: 'latest'

          - publish: $(outputDirectory)
            artifact: $(artifactName)
        

  - stage: AppCenterDeploy
    displayName: Deploy to App Center
    jobs:

      - job: AppCenter

        steps:

        - download: current
          artifact: $(artifactName)

        - task: AndroidSigning@3
          inputs:
            apkFiles: $(Pipeline.Workspace)/$(artifactName)/$(apkPath)
            apksignerKeystoreFile: $(keyStoreFile)
            apksignerKeystorePassword: '$(keystore.password)'
            apksignerKeystoreAlias: 'key0'
            apksignerKeyPassword: '$(key.password)'

        - task: AppCenterDistribute@3
          inputs:
            serverEndpoint: 'My App Center'
            appSlug: $(appCenterSlug)
            appFile: $(Pipeline.Workspace)/$(artifactName)/$(apkPath)
            symbolsOption: 'Android'
            releaseNotesOption: 'input'
            releaseNotesInput: 'The lazy developer hasn''t added any actual release notes.'
            destinationType: 'groups'
          

